version: "3" 

services:
  redis-db:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass secret1234

  rcli:
    image: redis:latest
    links:
      - redis-db
    command: redis-cli -h redis-db

  db:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret1234
      MYSQL_DATABASE: estoque
      MYSQL_USER: root
      MYSQL_PASSWORD: secret1234
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080